language: node_js
node_js:
    - '10'
dist: trusty # needs Ubuntu Trusty
sudo: required
addons:
    chrome: stable # have Travis install Chrome stable.
script:
    - npm test
    - npm run build-dist
branches:
    only:
        - master
